export const orgAbbreviations = [
    { abbr: 'ACSS', meaning: 'Association of Computer Studies Students' },
    { abbr: 'ALAS', meaning: 'Association of Liberal Arts Students' },
    { abbr: 'AMMS', meaning: 'Association of Marketing Management Students' },
    { abbr: 'ASA', meaning: 'Association of Student Assistants' },
    { abbr: 'CABE', meaning: 'College of Accountancy, Business and Entrepreneurship' },
    { abbr: 'CCIS', meaning: 'College of Computing and Information Sciences' },
    { abbr: 'CEDAS', meaning: 'College of Education, Arts and Sciences' },
    { abbr: 'CHS', meaning: 'College of Health Sciences' },
    { abbr: 'CSP', meaning: 'College of Special Programs' },
    { abbr: 'CSPSG', meaning: 'College of Special Programs Student Government' },
    { abbr: 'CSG', meaning: 'College Student Government' },
    { abbr: 'CBC', meaning: 'Crime Buster Club' },
    { abbr: '', meaning: 'Innovators' },
    { abbr: 'JAHM', meaning: 'Junior Association of Hospitality Management' },
    { abbr: 'JEBA', meaning: 'Junior Executives of Business Administration' },
    { abbr: 'JFINEX-Regular College', meaning: 'Junior Financial Executives' },
    { abbr: 'JFINEX-CSP', meaning: 'Junior Financial Executives' },
    { abbr: 'JPAMA', meaning: 'Junior Philippine Association of Management Accountants' },
    { abbr: 'JPICE', meaning: 'Junior Philippine Institute of Civil Engineers' },
    { abbr: 'JPIA', meaning: 'Junior Philippine Institute of Accountants' },
    { abbr: 'JPMAP-Regular College', meaning: 'Junior People Management Association of the Philippines' },
    { abbr: 'JPMAP-CSP', meaning: 'Junior People Management Association of the Philippines' },
    { abbr: 'KAMAFIL-Regular College', meaning: 'Kapisanan ng mga Mag-aaral sa Filipino' },
    { abbr: 'KAMAFIL-Socialize', meaning: 'Kapisanan ng mga Mag-aaral sa Filipino' },
    { abbr: 'LESCIEM', meaning: 'League of Science Majors' },
    { abbr: '', meaning: 'Math Club' },
    { abbr: 'OPEM-Regular', meaning: 'Organization of Physical Education Major' },
    { abbr: 'OPEM-Socialize', meaning: 'Organization of Physical Education Major' },
    { abbr: 'PFC', meaning: 'Peer Facilitators’ Club' },
    { abbr: 'PNSA', meaning: 'Philippine Nursing Student Association' },
    { abbr: 'RCY', meaning: 'Red Cross Youth' },
    { abbr: 'START', meaning: 'Student Association of Radiologic Technology' },
    { abbr: 'SEEDS', meaning: 'Society of Elementary Education Students' },
    { abbr: 'SEM-Regular College', meaning: 'Society of English Majors' },
    { abbr: 'SEM-CSP', meaning: 'Society of English Majors' },
    { abbr: 'SJP', meaning: 'Society of Junior Psychologists' },
    { abbr: 'SOMAMA', meaning: 'Society of Math Majors' },
    { abbr: '', meaning: 'TerpsiCORean Performing Group' },
    { abbr: '', meaning: 'Vocation Club/Hummingbirds/Lectors' },
    { abbr: 'YIS', meaning: 'Young Information Specialist' },
    { abbr: 'YFC', meaning: 'Youth for Christ' }
];